//---------------------------------------------------------------------------------------------------------------------
//
//---------------------------------------------------------------------------------------------------------------------
#include <exception>
#include <iostream>

int x[100];

int main(int /*argc*/, char** /*argv*/)
{
    try
    {
        std::cout << "Hello, World!";
        x[100] = 5;
    }
    catch (const std::exception& ex)
    {
        std::cout << "Exception: " << ex.what();
    }
}
